#!/bin/bash


# make sure user is root
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root." 
	exit 1
fi


# login info for ansible
#read -p "Ssh username (needs sudo power): " ssh_username
#read -s -p "Ssh password: " ssh_password

echo ''

# skip installing ansible if already installed
if ! command -v ansible > /dev/null 2>&1; then
	mount -o remount,size=10g /
        mkdir -p /new_root
	cd /new_root
	wget https://gentoo.osuosl.org/releases/amd64/autobuilds/current-stage3-amd64/stage3-amd64-20190703T214502Z.tar.xz -O stage3-amd64.tar.xz
	tar xf stage3-amd64.tar.xz
	cd usr
	wget https://gentoo.osuosl.org/snapshots/portage-latest.tar.xz -O portage-latest.tar.xz
	tar xf portage-latest.tar.xz
	
	/mnt/livecd/bin/ln -sfn /new_root/bin /bin
	/mnt/livecd/bin/ln -sfn /new_root/boot /boot
	
	mv /etc /etc_old
	/mnt/livecd/bin/ln -s /new_root/etc /etc
	cp -L /etc_old/resolv.conf /etc/resolv.conf
	
	/mnt/livecd/bin/ln -sfn /new_root/lib64 /lib64
	/mnt/livecd/bin/ln -sfn /new_root/opt /opt
	/mnt/livecd/bin/ln -sfn /new_root/sbin /sbin
	/mnt/livecd/bin/ln -sfn /new_root/usr /usr
	
	emerge --sync
        eselect profile set 1
	
	sed -i '/^COMMON_FLAGS=/c\COMMON_FLAGS="-march=native -O0 -pipe"' /etc/portage/make.conf
	echo "MAKEOPTS=\"-j6\"" >> /etc/portage/make.conf
	echo "EMERGE_DEFAULT_OPTS=\"--jobs 6\"" >> /etc/portage/make.conf
	
	USE="-nls" emerge =sys-apps/help2man-1.47.6
   	emerge dev-vcs/git
	
	USE="sqlite" emerge =dev-lang/python-3.6.5
	USE="sqlite" emerge =dev-lang/python-2.7.15:2.7
	
	emerge app-admin/ansible
	emerge app-admin/ansible
	
	mkdir -p gentoo_install_repo
	git clone https://github.com/andrew-klassen/gentoo_installer.git gentoo_install_repo

else

	echo ''
	echo ''
	echo "Ansible is installed. Skipping ansible Installation."

fi


#cd ansible

#ansible-playbook install.yml -e "ansible_user=${ssh_username} ansible_ssh_pass=${ssh_password} ansible_sudo_pass=${ssh_password}"	
