#!/bin/bash


# make sure user is root
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root." 
	exit 1
fi


# login info for ansible
read -p "Ssh username (needs sudo power): " ssh_username
read -s -p "Ssh password: " ssh_password

echo ''

# skip installing ansible if already installed
if ! command -v ansible > /dev/null 2>&1; then
        emerge --sync
        eselect profile set 1
	emerge --keep-going app-admin/ansible	

else

	echo ''
	echo ''
	echo "Ansible is installed. Skipping ansible Installation."

fi


cd ansible

#ansible-playbook install.yml -e "ansible_user=${ssh_username} ansible_ssh_pass=${ssh_password} ansible_sudo_pass=${ssh_password}"	

