
- name: install dependencies
  portage:
    name: "{{ packages }}"
  vars:
    packages:
    - sys-block/gparted

- name: create esp partition
  parted:
    device: /dev/sda
    number: 1
    label: gpt
    part_end: 100MB
    state: present

- name: create / partion
  parted:
    device: /dev/sda
    number: 2
    label: gpt
    part_start: 100MB
    state: present

